### ISSUE TITLE
bump mbed-os version

### ISSUE THREAD

**Issue by dlfryar-zz** [ARMmbed/mbed-os-example-spiflash-driver#3]
@adbridge can we bump the mbed-os version on this repo to at least 5.9.2?

**Comment by adbridge** [comment]
@dlfryar As far as I am aware this isn't an officially supported example yet and thus is not getting tested or updated for releases...

**Comment by dlfryar-zz** [comment]
Thanks, closing until it is officially supported.  Is there a label or disclaimer that should be added to this repo that shows it's unsupported?
